### PR TITLE
v1 #743

### PR DESCRIPTION
**Pull request by jstet**
- Changed Filter component so checkboxes can dynamically be included

- Added Icon to right corner of projects card
- added application link in cms and to the card and single project view

@pr130 If you agree with these changes (see deployed preview), feel free to accept the PR

### CODE REVIEW

**Comment by jstet** [comment]
Whoops typo

**Comment by pr130** [comment]
Thanks @jstet : 
- clicking on the icon gives 404 -> https://775d37a2.correlaid.pages.dev/en/using-data/project-database/google.com/ -> should this even be clickable? i do not think it's necessary. 
- regarding the icon: can we do something that is more "search" oriented? or "team"? or "application"? there are some icons on the icon noun project but i can't figure out how to download them (and the website is extra buggy right now 😭 ) 
- no prio but minor bug: if you tick the checkbox and change the language, the checkbox remains ticked, but it's not filtered anymore and all projects are shown. but i suppose this is one of those "looks minor but is complicated things" so no prio on that bc that is not a regular user behaviour. :D 

changed myself and pushed (hopefully you agree): 
- checkbox filter wording in german: change to "Bewerbungsphase läuft"
- Jetzt bewerben and Apply now instead of only bewerben/apply

**Comment by jstet** [comment]
- Icon link mistakenly survived from former icon. thanks for removing it.
- language change issue: https://github.com/CorrelAid/correlaid_website/issues/763 this is also a problem for the selects, i will fix it later :D
- i will look for a new icon
- re the "jetzt bewerben" field instead of link: I agree with avoiding the shortcut. However I am not sure if we should use the correlaidx colour for stuff like this and i feel adding a notice like that looks a bit disruptive and too vanilla. also with the icon, the teaser we would have three indications that one can apply and i feel like thats too much.

**Comment by jstet** [comment]
Btw my logic re the icon was that we also used it in the ctas at the bottom of https://www.correlaid.org/bildung/r-lernen/

**Comment by jstet** [comment]
@pr130 could u send the link to the icons you liked. I found this one: https://thenounproject.com/icon/search-profile-4223974/

**Comment by pr130** [comment]
this looks great!

**Comment by pr130** [comment]
that looks great!


(er/ihm)


PS: Ich habe meinen Vornamen von Frie zu Leo geändert. Meine neue
Email-Adresse ist ***@***.*** Ich bitte um zeitnahes Updaten von
Adressbuch-Einträgen. Emails an ***@***.*** werden vorerst
weiterhin an mich zugestellt.

*--*
Leo Preu

Head of Data4Good Projects | Referent*in Civic Data Lab
CorrelAid e.V.


*#GernePerDu mit entgenderter ("Hi/Hallo Leo" oder "Liebe*r Leo") oder
maskuliner ("Lieber Leo") Anrede. *
*Formal: „Guten Tag Leo Preu", „Sehr geehrte*r Leo Preu“ oder "Sehr
geehrter Herr Preu".*

**Comment by pr130** [comment]
re wording: good point.. then we just have to use the teaser field to write something like "apply now!" . i'll make note of that for the project people. 📝 then i'd opt for nothing at all below the teaser.

**Comment by jstet** [comment]
Alrighty, thanks. I will implement what we agreed on :)

**Pull request merged**
