### PR TITLE
closes #414

### LINKED ISSUE #414: Icons Navigation
all icons as svg files: https://drive.google.com/drive/folders/1Mpj8zviJzzZpBLed-PUL0iX0oG6NYeQk?usp=sharing

Canva layout for new icons if needed: https://www.canva.com/design/DAFjp1tY_20/_pSFvih-nYkt8ZLGRLNsKA/edit?utm_content=DAFjp1tY_20&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

### PR DESCRIPTION
**Pull request by jstet**

### CODE REVIEW

**Comment by jstet** [comment]
waiting for confirmation via slack

**Comment by friep** [comment]
Thanks! I like the elements and think that they could be useful on other pages (obvious: "Bildung" where there is a screenshot of exactly those icons). 

Looking at them on my big ass monitor screen, i have two concerns:

- font: i don't think the font is well readable from an accessibility perspective when it is so small. i know we have been using it on canva for a bit but i feel for this, it is not so well suited (the letters "mush together" even for me). 
- colors: maybe we could think about different colors for the backgrounds of the icons? in `[correltools](https://github.com/CorrelAid/correltools)` , there the opportunity to create qualitative palettes: 

```
scales::show_col(correltools::correlaid_pal()(5))
```

Screenshot 2023-05-31 at 15 37 10

or is this too many different colors? IDK.

**Comment by jstet** [comment]
> Thanks! I like the elements and think that they could be useful on other pages.
> 
> Looking at them on my big ass monitor screen, i have two concerns:
> 
>     * font: i don't think the font is well readable from an accessibility perspective when it is so small. i know we have been using it on canva for a bit but i feel for this, it is not so well suited (the letters "mush together" even for me).
> 
>     * colors: maybe we could think about different colors for the backgrounds of the icons? I think right now it implies too much of a "sequence". in `[correltools](https://github.com/CorrelAid/correltools)` , there the opportunity to create qualitative palettes:
> 
> 
> ```
> scales::show_col(correltools::correlaid_pal()(5))
> ```
> 
> Screenshot 2023-05-31 at 15 37 10
> 
> or is this too many different colors? IDK.

@friep i have increased the font spacing, size etc. Does it work better now?

I intentionally used a sequence of colours so it fits to the gradient of the hero etc.

**Comment by jstet** [comment]
I will merge for now because i edited texts in the cms that are based on this change and this is blocking the build for other changes.

**Pull request merged**
