### PR TITLE
#249: more typical styling for inline code

### LINKED ISSUE #249: Syntax highlighting
not sure this is something that has to do with directus or whether we can do this in svelte later (i tried to do it myself but had to give up.. ) 

example post in directus: https://cms.correlaid.org/admin/content/Posts/58
example post online: https://preview.correlaid.org/en/blog/newsanchor-vignette/

not only code blocks but also inline code - right now with "`" which is ok but nto suuper nice

### PR DESCRIPTION
**Pull request by friep**
adds more "typical" styling for inline code.  i hope this is not too controversial and we don't have to do a poll for it?! :D  lots of other people also don't like the default. https://github.com/tailwindlabs/tailwindcss-typography/issues/18

i copied and adapted from here: https://futurestud.io/tutorials/tailwind-css-remove-backticks-around-inline-code

before:

Screenshot 2023-05-09 at 12 27 45

after:

Screenshot 2023-05-09 at 12 27 21

closes #249 which i reopened to add this.

### CODE REVIEW

**Comment by KonradUdoHannes** [comment]
Can we reopen another PR. I think your extensive description can be copied from edit mode so it should not be too much trouble.

**Comment by friep** [comment]
@KonradUdoHannes ahhh yesss... i changed the base branch here (that's actually possible :)) . thanks for the quick feedback!!

**Comment by KonradUdoHannes** [comment]
@friep cool I didn't know this can just be changed. Also next time its best to make a fork from preview in which case the commit won't contain all our previous merge commits (which don't actually change anything because they all come from `preview` itself).

Maybe we should go from `main` / `preview` to `production` / `main` as branches where the new main takes the role of the old preview and the new `production` of the old `main` (Changing the cloudflare CD settings accordingly). This would probably make it more intuitive for contributors as it would then involve the more normal branch and merge into `main` pattern. @jstet what do you think.

**Comment by friep** [comment]
this is deflecting a bit from the OT but imho this pattern is ok! i like `main` being the default branch reflecting the current state of the website. I think documenting this in the README a bit more and giving contributors a heads-up where to merge off from would be sufficient :) was also partially my fault for not reading the README where it says "Merge with preview, then merge with master." - kind of implying a merge off from preview for development purposes. :)

**Pull request merged**
